server:
  port: 8080
spring:
  application:
    name: management
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: ${POSTGRES_USER:myuser}
    password: ${POSTGRES_PASSWORD:mypassword}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: false
