-- Masones
CREATE TABLE IF NOT EXISTS masons (
mason_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(50) NOT NULL,
second_name VARCHAR(50) DEFAULT NULL,
last_name VARCHAR(50) NOT NULL,
second_last_name VARCHAR(50) DEFAULT NULL,
date_of_birth DATE NOT NULL,
is_free_member BOOLEAN,
created_at TIMESTAMP NOT NULL,
created_by VARCHAR(20) NOT NULL,
updated_at TIMESTAMP DEFAULT NULL,
updated_by VARCHAR(20) DEFAULT NULL
);

-- Datos de contacto
CREATE TABLE IF NOT EXISTS mason_contacts (
contact_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
mason_id INT NOT NULL UNIQUE,
mobile VARCHAR(20) NOT NULL UNIQUE,
email VARCHAR(100) NOT NULL UNIQUE,
address VARCHAR(255) DEFAULT NULL,
emergency_contact_name VARCHAR(100) NOT NULL,
emergency_contact_phone VARCHAR(20) NOT NULL,
contact_preference VARCHAR(10) NOT NULL CHECK (contact_preference IN ('EMAIL', 'PHONE')),
notes TEXT DEFAULT NULL,
created_at TIMESTAMP NOT NULL,
created_by VARCHAR(20) NOT NULL,
updated_at TIMESTAMP DEFAULT NULL,
updated_by VARCHAR(20) DEFAULT NULL,
FOREIGN KEY (mason_id) REFERENCES masons(mason_id) ON DELETE CASCADE
);

-- Oficios de la logia
CREATE TABLE IF NOT EXISTS lodge_offices (
office_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
office_name VARCHAR(50) NOT NULL UNIQUE,
created_at TIMESTAMP NOT NULL,
created_by VARCHAR(20) NOT NULL,
updated_at TIMESTAMP DEFAULT NULL,
updated_by VARCHAR(20) DEFAULT NULL
);

-- Historial de masones en oficios
CREATE TABLE IF NOT EXISTS mason_offices (
mason_office_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
mason_id INT NOT NULL,
office_id INT NOT NULL,
start_date DATE NOT NULL,
end_date DATE DEFAULT NULL,
appointed_by INT NOT NULL,
created_at TIMESTAMP NOT NULL,
created_by VARCHAR(20) NOT NULL,
updated_at TIMESTAMP DEFAULT NULL,
updated_by VARCHAR(20) DEFAULT NULL,
FOREIGN KEY (mason_id) REFERENCES masons(mason_id),
FOREIGN KEY (office_id) REFERENCES lodge_offices(office_id),
FOREIGN KEY (appointed_by) REFERENCES masons(mason_id)
);

-- Conceptos de ingreso
CREATE TABLE IF NOT EXISTS income_concepts (
income_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
description VARCHAR(100) NOT NULL,
created_at TIMESTAMP NOT NULL,
created_by VARCHAR(20) NOT NULL,
updated_at TIMESTAMP DEFAULT NULL,
updated_by VARCHAR(20) DEFAULT NULL
);

-- Transacciones de ingreso
CREATE TABLE IF NOT EXISTS income_transactions (
transaction_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
mason_id INT NOT NULL,
concept INT NOT NULL,
amount DECIMAL(10,2) NOT NULL,
payment_date DATE NOT NULL,
payment_method VARCHAR(30) NOT NULL,
receipt_number VARCHAR(30) NOT NULL,
notes TEXT,
created_at TIMESTAMP NOT NULL,
created_by VARCHAR(20) NOT NULL,
updated_at TIMESTAMP DEFAULT NULL,
updated_by VARCHAR(20) DEFAULT NULL,
FOREIGN KEY (mason_id) REFERENCES masons(mason_id),
FOREIGN KEY (concept) REFERENCES income_concepts(income_id)
);

-- Transacciones de egreso
CREATE TABLE IF NOT EXISTS expense_transactions (
expense_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
description VARCHAR(200) NOT NULL,
amount DECIMAL(10,2) NOT NULL,
expense_date DATE NOT NULL,
category VARCHAR(50),
approved_by INT NOT NULL,
receipt_attachment VARCHAR(255),
created_at TIMESTAMP NOT NULL,
created_by VARCHAR(20) NOT NULL,
updated_at TIMESTAMP DEFAULT NULL,
updated_by VARCHAR(20) DEFAULT NULL,
FOREIGN KEY (approved_by) REFERENCES masons(mason_id)
);

-- Grados masónicos
CREATE TABLE IF NOT EXISTS mason_degrees (
degree_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
mason_id INT NOT NULL,
degree_type VARCHAR(2) NOT NULL CHECK (degree_type IN ('AM', 'CM', 'MM')),
received_date DATE NOT NULL,
conferred_by INT,
notes VARCHAR(250),
created_at TIMESTAMP NOT NULL,
created_by VARCHAR(20) NOT NULL,
updated_at TIMESTAMP DEFAULT NULL,
updated_by VARCHAR(20) DEFAULT NULL,
FOREIGN KEY (mason_id) REFERENCES masons(mason_id),
FOREIGN KEY (conferred_by) REFERENCES mason_offices(mason_office_id)
);

-- Saco de beneficencia
CREATE TABLE IF NOT EXISTS charity_bag_circulations (
circulation_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
circulation_date DATE NOT NULL,
amount_collected DECIMAL(10,2) NOT NULL,
handled_by INT NOT NULL,
notes TEXT,
created_at TIMESTAMP NOT NULL,
created_by VARCHAR(20) NOT NULL,
updated_at TIMESTAMP DEFAULT NULL,
updated_by VARCHAR(20) DEFAULT NULL,
FOREIGN KEY (handled_by) REFERENCES masons(mason_id)
);

-- Historial de estados por hermano
CREATE TABLE IF NOT EXISTS mason_status_history (
history_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
mason_id INT NOT NULL,
status BOOLEAN NOT NULL,
change_date DATE NOT NULL,
reason VARCHAR(255) DEFAULT NULL,
outstanding_debt DECIMAL(10,2) DEFAULT 00,
created_at TIMESTAMP NOT NULL,
created_by VARCHAR(20) NOT NULL,
updated_at TIMESTAMP DEFAULT NULL,
updated_by VARCHAR(20) DEFAULT NULL,
FOREIGN KEY (mason_id) REFERENCES masons(mason_id)
);

-- Historial de precios de conceptos de ingreso
CREATE TABLE IF NOT EXISTS concept_price_history (
price_history_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
concept_id INT NOT NULL,
amount DECIMAL(10,2) NOT NULL,
effective_from DATE NOT NULL,
effective_to DATE DEFAULT NULL,
created_at TIMESTAMP NOT NULL,
created_by VARCHAR(20) NOT NULL,
updated_at TIMESTAMP DEFAULT NULL,
updated_by VARCHAR(20) DEFAULT NULL,
FOREIGN KEY (concept_id) REFERENCES income_concepts(income_id),
CONSTRAINT unique_active_price UNIQUE (concept_id, effective_to)
);

-- 1 Vista con el estado actual del masón (último registro del historial)
CREATE OR REPLACE VIEW v_masons_with_status AS
SELECT
    m.mason_id,
    m.name,
    m.second_name,
    m.last_name,
    m.second_last_name,
    m.date_of_birth,
    m.is_free_member,
    m.created_at,
    m.created_by,
    m.updated_at,
    m.updated_by,
    h.status AS current_status,
    h.change_date AS last_status_change,
    h.reason AS last_status_reason,
    h.outstanding_debt AS last_outstanding_debt
FROM masons m
LEFT JOIN mason_status_history h ON h.mason_id = m.mason_id
WHERE h.history_id = (
    SELECT history_id
    FROM mason_status_history h2
    WHERE h2.mason_id = m.mason_id
    ORDER BY h2.change_date DESC
    LIMIT 1
);